### ISSUE TITLE
gitstatus failed to initialize.

### ISSUE THREAD

**Issue by hopewise** [romkatv/gitstatus#294]
gitstatus failed to initialize when I use puma-dev to serve my ruby on rails app, as here:

```
! Booting app 'backend-4cc1c336' on socket /Users/samir/.puma-dev/admin.myapp/tmp/puma-dev-13166.sock
backend-4cc1c336[13820]: tput: No value for $TERM and no -T specified
backend-4cc1c336[13820]:
backend-4cc1c336[13820]: [ERROR]: gitstatus failed to initialize.
backend-4cc1c336[13820]:
backend-4cc1c336[13820]:   Your Git prompt may disappear or become slow.
backend-4cc1c336[13820]:
backend-4cc1c336[13820]:   Zsh log (/private/var/folders/75/twcpcdqj7q323p_ldn9ss0fc0000gn/T/gitstatus.MY.501.13820.1642684755.1.xtrace.log):
backend-4cc1c336[13820]:
backend-4cc1c336[13820]:     +(anon):7> setopt monitor
backend-4cc1c336[13820]:     (anon):setopt:7: can't change option: monitor
backend-4cc1c336[13820]:     +(anon):7> return
backend-4cc1c336[13820]:
backend-4cc1c336[13820]:   System information:
backend-4cc1c336[13820]:
backend-4cc1c336[13820]:     zsh:      5.8
backend-4cc1c336[13820]:     uname -a: Darwin 192.168.1.103 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
backend-4cc1c336[13820]:
backend-4cc1c336[13820]:   If you need help, open an issue and attach this whole error message to it:
backend-4cc1c336[13820]:
backend-4cc1c336[13820]:     https://github.com/romkatv/gitstatus/issues/new
backend-4cc1c336[13820]: Puma starting in single mode...
backend-4cc1c336[13820]: * Puma version: 5.5.2 (ruby 2.5.0-p0) ("Zawgyi")
backend-4cc1c336[13820]: *  Min threads: 0
backend-4cc1c336[13820]: *  Max threads: 5
backend-4cc1c336[13820]: *  Environment: development
backend-4cc1c336[13820]: *          PID: 13820
backend-4cc1c336[13820]: WARNING: Nokogiri was built against LibXML version 2.9.12, but has dynamically loaded 2.9.4
backend-4cc1c336[13820]: /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/redis-3.2.2/lib/redis/client.rb:441: warning: constant ::Fixnum is deprecated
backend-4cc1c336[13820]: /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/redis-3.2.2/lib/redis/client.rb:441: warning: constant ::Fixnum is deprecated
backend-4cc1c336[13820]: * Listening on unix:/Users/samir/.puma-dev/admin.myapp/tmp/puma-dev-13166.sock
backend-4cc1c336[13820]: /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- nio (LoadError)
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/reactor.rb:24:in `initialize'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/server.rb:242:in `new'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/server.rb:242:in `run'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/single.rb:53:in `run'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/launcher.rb:181:in `run'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/cli.rb:80:in `run'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/bin/puma:10:in `<top (required)>'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/bin/puma:23:in `load'
backend-4cc1c336[13820]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/bin/puma:23:in `<main>'
! App 'backend-4cc1c336' booted
2022/01/20 16:19:49 http: proxy error: EOF
! Killing 'backend-4cc1c336' (13820) - 'stdout/stderr closed'
* App 'backend-4cc1c336' shutdown and cleaned up
```

Any idea??

**Comment by hopewise** [comment]
Thanks @romkatv , Can you please elaborate more about `TTY`, any link or description would be highly appreciated.

**Comment by romkatv** [comment]
I mean https://en.wikipedia.org/wiki/Terminal_emulator. It doesn't make sense to use gitstatus without a terminal. gitstatus is for prompt, but there is no prompt without a terminal.
